# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RU1-DtBWxObVy25Sx9i754FEC_KjIfzg
"""

lista = ['cloroquina','dipirona','ivermectina','loratadina','antibiótico']
print('Um farmacêutico está na drogaria, quando chega um cliente. Dentre as opções:', lista) 
pedido = input('ele pede ')

if pedido == 'cloroquina' or pedido == 'ivermectina':
    print('ele deve perguntar se o paciente possui receita e qual a finalidade, se for covid.') 
    print(' O farmacêutico deve orientar o cliente que este medicamento não possui comprovação cinetífica para esta utiliação e que não irá vendê-lo.')
elif pedido == 'antibiótico':
    print('O farmacêutico deve perguntar se o paciente possui receita e retê-la na drogaria, além de fazer a orientação do uso adequado do medicamento')
elif pedido == 'loratadina' or pedido == 'dipirona':
     print('O farmacêutico deve fazer a venda, orientrando como fazer a devida utilização do medicamento e possíveis efeitos adversos')
else :
    print('Estamos sem estoque, lamento.')

